# Generated by Django 4.1.7 on 2024-11-26 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_email', models.CharField(max_length=40)),
                ('patient_phone', models.BigIntegerField()),
                ('patient_gender', models.CharField(max_length=15)),
                ('birth_date', models.DateField(null=True)),
                ('patient_age', models.PositiveIntegerField(blank=True, null=True)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('reference_no', models.CharField(default='', max_length=40)),
                ('patient_description', models.CharField(max_length=200)),
                ('patient_address', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_app.doctors')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common_app.patient')),
            ],
            options={
                'db_table': 'booking',
            },
        ),
    ]
